common:
  security:
    enabled: false
  feign-oauth:
    enabled: false
  mvc:
    enabled: false
server:
  ssl:
    enabled: false
  servlet:
    context-path: /badge-system
spring:
  security:
    user:
      name: user
      password: 123
  application:
    name: Electronic Badge/Attendance System
  datasource:
    username: ebas
    password: ebas
    url: jdbc:postgresql://localhost:5432/ebas
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always