POST http://localhost:8080/v1/badge-system/roles
Authorization: Basic user 123
Content-Type: application/json

{
  "name": "student",
  "defaultAccountTypes" : [{"id": 1}, {"id": 2}, {"id": 3}]
}

###

POST http://localhost:8080/v1/badge-system/roles
Authorization: Basic user 123
Content-Type: application/json

{
  "name": "staff",
  "defaultAccountTypes" : [{"id": 2}, {"id": 3}]
}

###

POST http://localhost:8080/v1/badge-system/roles
Authorization: Basic user 123
Content-Type: application/json

{
  "name": "faculty",
  "defaultAccountTypes" : [{"id": 1}, {"id": 2}]
}

###
GET http://localhost:8080/v1/badge-system/roles
Authorization: Basic user 123