GET http://localhost:8080/v1/badge-system/locations

###
POST http://localhost:8080/v1/badge-system/locations
Authorization: Basic user 123
Content-Type: application/json

{
  "name": "agriro",
  "locationType": "DINING_HALL"
}
####

POST http://localhost:8080/v1/badge-system/locations
Authorization: Basic user 123
Content-Type: application/json

{
"name": "Dybr HALL",
"locationType": "CLASSROOM"
}

###
PUT http://localhost:8080/v1/badge-system/locations/1
Authorization: Basic user 123
Content-Type: application/json

{
  "id": 1,
"name": "ARGIRO ROCKS!",
"locationType": "DINING_HALL"
}

###
GET http://localhost:8080/v1/badge-system/locations/1
Authorization: Basic user 123

###
#DELETE http://localhost:8080/v1/badge-system/locations/1
#Authorization: Basic user 123


POST http://localhost:8080/v1/badge-system/locations
Authorization: Basic user 123
Content-Type: application/json

{
  "id": 5,
  "name": "adonay",
  "locationType": "RESTAURANT"
}