GET http://localhost:8080/v1/badge-system/members
Authorization: Basic user 123

###
POST http://localhost:8080/v1/badge-system/members
Authorization: Basic user 123
Content-Type: application/json

{
  "firstname": "Jean Claude",
  "lastname": "GOMBANIRO",
  "email": "jgombaniro@miu.edu",
  "barcode": "123456789012"
}

###
POST http://localhost:8080/v1/badge-system/members
Authorization: Basic user 123
Content-Type: application/json

{
  "firstname": "Joe",
  "lastname": "Doe",
  "email": "joe@miu.edu",
  "barcode": "123456789013"
}

###
POST http://localhost:8080/v1/badge-system/members
Authorization: Basic user 123
Content-Type: application/json

{
  "firstname": "Jilly",
  "lastname": "Layman",
  "email": "layman@miu.edu",
  "barcode": "123456789014"
}

###

GET http://localhost:8080/v1/badge-system/members/1
Authorization: Basic user 123

###

###
PUT http://localhost:8080/v1/badge-system/members/1
Authorization: Basic user 123
Content-Type: application/json

{
  "id": 1,
  "firstname": "Jean Claude",
  "lastname": "Gombaniro",
  "email": "jgombaniro@miu.edu",
  "barcode": "123456789012"
}

###
POST http://localhost:8080/v1/badge-system/members
Authorization: Basic user 123
Content-Type: application/json

{
  "firstname": "James",
  "lastname": "Layman",
  "email": "james@miu.edu",
  "barcode": "123456789015",
  "roles": [
    {
      "id":1
    }
  ]
}

###
GET http://localhost:8080/v1/badge-system/members/4/roles
Authorization: Basic user 123
Content-Type: application/json


###
PUT http://localhost:8080/v1/badge-system/members/4/roles
Authorization: Basic user 123
Content-Type: application/json

{
  "id": 4,
  "firstname": "James",
  "lastname": "Layman",
  "email": "james@miu.edu",
  "barcode": "123456789016",
  "roles": [
    {
      "id":2
    }
  ]
}
###

#DELETE http://localhost:8080/v1/badge-system/members/4/roles/1
#Authorization: Basic user 123
#Content-Type: application/json

###
PUT http://localhost:8080/v1/badge-system/members/2
Authorization: Basic user 123
Content-Type: application/json

{
  "id": 2,
  "firstname": "Joe",
  "lastname": "Doe",
  "email": "joe@miu.edu",
  "barcode": "123456789013",
  "roles": [
    {
      "id":2
    },
    {
      "id":1
    }
  ]
}
