GET http://localhost:8080/v1/badge-system/records
Authorization: Basic user 123

###
POST http://localhost:8080/v1/badge-system/records
Authorization: Basic user 123
Content-Type: application/json

{
  "member": {"id":  1},
  "session":{"id": 1}
}

###
POST http://localhost:8080/v1/badge-system/records
Authorization: Basic user 123
Content-Type: application/json

{
  "member": {"id":  1},
  "session":{"id": 2}
}

###
POST http://localhost:8080/v1/badge-system/records
Authorization: Basic user 123
Content-Type: application/json

{
  "member": {"id":  1},
  "session":{"id": 4}
}